### ISSUE TITLE
gathering requirements

### ISSUE THREAD

**Issue by Egosum1210** [Egosum1210/lab2-sw-nw#1]
SubTasks:
 
 * [x]  [1. analyze domain area #2](#2)
 * [ ]   [2. Write software requirement specification #3](#3)
 * [ ]  [3. Draw Use-case diagram #4](#4)
